### PR TITLE
Basic implementation of Docker

### PR DESCRIPTION
**Pull request by DebitCardz**
This is my first time ever properly setting up docker for a project, reviews on this would genuinely be appreciated.

### CODE REVIEW

**Review by Authorises — APPROVED** [review]
Docker looks good 👍

**Comment by DebitCardz** [comment]
@Authorises, for some reason gradle isn't caching it's builds so it takes around a minute to recompile images.
Is there a specific command that needs to be used or anything in the Dockerfile that needs to be changed?

**Comment by Authorises** [comment]
> @Authorises, for some reason gradle isn't caching it's builds so it takes around a minute to recompile images.
> Is there a specific command that needs to be used or anything in the Dockerfile that needs to be changed?

- I'm not aware of any non-enterprise solutions for this (https://hub.docker.com/gradle/build-cache-node)

**Comment by DebitCardz** [comment]
We could use docker hub since we're open source but local builds aren't caching either which is the troubling part 😒
I'll research more into how to deploy JVM applications later since this is a big deal before I merge this PR.

**Pull request merged**
